feat: #88 adds login functionality with requests example
smartive-education/app-musketeers pull request #13
Opened 2023-03-19 14:09 UTC by samumic

2023-03-20 14:42 UTC, monobasic commented on components/comment-interaction.tsx
> +interface CommentInteractionProps {
I would use type here instead of interface, after the discussion in school.. seems to be the better approach, although I don't remember why exactly thb.

2023-03-20 14:43 UTC, monobasic commented on components/header.tsx
> +          <NavigationItem label="Logout" onClick={() => signOut()}>
Is the anonymous arrow function wrapper needed here? Not sure, was just wondering..

2023-03-20 14:44 UTC, monobasic commented on components/like-interaction.tsx
> +interface LikeInteractionProps {
same here -> type

2023-03-23 09:03 UTC, monobasic requested changes
Good work mate!
Only thing is the use of interface vs. type, I think we should go with type.
Apart from that, I am not sure right now if some of the auth logic needs to be moved to _app.js laters and also the redirect logic in index.tsx, basically this should be there for all possible urls, when a user is not logged in, but let's discuss this in a call!

2023-03-23 18:53 UTC, samumic commented on components/header.tsx
> +          <NavigationItem label="Logout" onClick={() => signOut()}>
Yes! Since only calling signOut() will pass the return value as a prop

2023-03-23 19:59 UTC, monobasic approved these changes
LEGIT!

2023-03-23 19:59 UTC, merged